name: go-todos-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies and Build React App
      working-directory: ./client
      run: |
        npm ci
        npm run build 
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Golang App
      run: go build -v ./cmd/web/...

    - name: Test
      run: go test -v ./...
      
      
  publish:
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) }} 
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mananwalia959/go-todos-app:${{ github.sha }},mananwalia959/go-todos-app:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: [publish] # Only run this workflow when "publish" workflow succeeds
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docker App
      run: echo "Placeholder step"



