name: go-todos-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies and Build React App
      working-directory: ./client
      run: |
        npm ci
        npm run build 
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Golang App
      run: go build -v ./cmd/web/...

    - name: Test
      run: go test -v ./...
      
      
  publishDockerArtifact:
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) }} 
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mananwalia959/go-todos-app:${{ github.sha }},mananwalia959/go-todos-app:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: [publishDockerArtifact] # Only run this workflow when "publishDockerArtifact" workflow succeeds
    environment: 'production'
    steps:
    - name: Deploy Publish Artifact
      uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        script_stop: true
        script: | 
          docker container rm -f todo || true
          docker image prune -a -f
          echo "I am Here 2"

